version: '3.5'
services:
  backend:
    container_name: stellar-cd
    image: nmluci/stellar-cd:1.1.0
    build: 
      context: .
      args:
        USERNAME_GITHUB: nmluci
        TOKEN_GITHUB: 
    ports:
      - "3980:7780"
      - "3981:7781"
    volumes:
      - ~/deployment/config:/config:ro
      - ~/deployment/script:/script:ro
      - ~/services:/services
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
networks:
  default:
    name: stellar-net
    external: true