version: '3.3'
services:
  backend:
    container_name: stellar-cd
    image: nmluci/stellar-cd:0.0.1-alpha
    build: .
    ports:
      - "3980:7780"
      - "3981:7781"
networks:
  default:
    name: stellar-net
    external: true