version: '3.5'
services:
  backend:
    container_name: stellar-cd
    image: nmluci/stellar-cd:0.0.1
    build: 
      context: .
      args:
        USERNAME_GITHUB: nmluci
        TOKEN_GITHUB: 
    ports:
      - "3980:7780"
      - "3981:7781"
    volumes:
      - /home/misaki/deployment/config:/config:ro
      - /home/misaki/deployment/script:/script:ro
      - /home/misaki/services:/services:ro
networks:
  default:
    name: stellar-net
    external: true