// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: fileop.proto

package fileop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XId      int64  `protobuf:"varint,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Filesize int64  `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_fileop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_fileop_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetXId() int64 {
	if x != nil {
		return x.XId
	}
	return 0
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

type Files struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []*File `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Collection string  `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Requester  string  `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
}

func (x *Files) Reset() {
	*x = Files{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Files) ProtoMessage() {}

func (x *Files) ProtoReflect() protoreflect.Message {
	mi := &file_fileop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Files.ProtoReflect.Descriptor instead.
func (*Files) Descriptor() ([]byte, []int) {
	return file_fileop_proto_rawDescGZIP(), []int{1}
}

func (x *Files) GetData() []*File {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Files) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Files) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type FileQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	IsBundle   bool   `protobuf:"varint,2,opt,name=is_bundle,json=isBundle,proto3" json:"is_bundle,omitempty"`
	Requester  string `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
}

func (x *FileQuery) Reset() {
	*x = FileQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileQuery) ProtoMessage() {}

func (x *FileQuery) ProtoReflect() protoreflect.Message {
	mi := &file_fileop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileQuery.ProtoReflect.Descriptor instead.
func (*FileQuery) Descriptor() ([]byte, []int) {
	return file_fileop_proto_rawDescGZIP(), []int{2}
}

func (x *FileQuery) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FileQuery) GetIsBundle() bool {
	if x != nil {
		return x.IsBundle
	}
	return false
}

func (x *FileQuery) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type FileArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename   string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Collection string `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	IsFile     bool   `protobuf:"varint,3,opt,name=is_file,json=isFile,proto3" json:"is_file,omitempty"`
	Requester  string `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
}

func (x *FileArchive) Reset() {
	*x = FileArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileArchive) ProtoMessage() {}

func (x *FileArchive) ProtoReflect() protoreflect.Message {
	mi := &file_fileop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileArchive.ProtoReflect.Descriptor instead.
func (*FileArchive) Descriptor() ([]byte, []int) {
	return file_fileop_proto_rawDescGZIP(), []int{3}
}

func (x *FileArchive) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileArchive) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FileArchive) GetIsFile() bool {
	if x != nil {
		return x.IsFile
	}
	return false
}

func (x *FileArchive) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_fileop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_fileop_proto_rawDescGZIP(), []int{4}
}

var File_fileop_proto protoreflect.FileDescriptor

var file_fileop_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x22, 0x61, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0f,
	0x0a, 0x03, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x67, 0x0a, 0x05, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x22, 0x66, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x98, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x65, 0x6c, 0x6c,
	0x61, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x11, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x0d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a,
	0x0d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x6f, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x6d, 0x6c, 0x75, 0x63, 0x69, 0x2f, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2d, 0x66,
	0x69, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileop_proto_rawDescOnce sync.Once
	file_fileop_proto_rawDescData = file_fileop_proto_rawDesc
)

func file_fileop_proto_rawDescGZIP() []byte {
	file_fileop_proto_rawDescOnce.Do(func() {
		file_fileop_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileop_proto_rawDescData)
	})
	return file_fileop_proto_rawDescData
}

var file_fileop_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fileop_proto_goTypes = []interface{}{
	(*File)(nil),        // 0: fileop.File
	(*Files)(nil),       // 1: fileop.Files
	(*FileQuery)(nil),   // 2: fileop.FileQuery
	(*FileArchive)(nil), // 3: fileop.FileArchive
	(*Empty)(nil),       // 4: fileop.Empty
}
var file_fileop_proto_depIdxs = []int32{
	0, // 0: fileop.Files.data:type_name -> fileop.File
	2, // 1: fileop.StellarFile.Search:input_type -> fileop.FileQuery
	1, // 2: fileop.StellarFile.Download:input_type -> fileop.Files
	3, // 3: fileop.StellarFile.Archive:input_type -> fileop.FileArchive
	1, // 4: fileop.StellarFile.Search:output_type -> fileop.Files
	4, // 5: fileop.StellarFile.Download:output_type -> fileop.Empty
	4, // 6: fileop.StellarFile.Archive:output_type -> fileop.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fileop_proto_init() }
func file_fileop_proto_init() {
	if File_fileop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Files); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileop_proto_goTypes,
		DependencyIndexes: file_fileop_proto_depIdxs,
		MessageInfos:      file_fileop_proto_msgTypes,
	}.Build()
	File_fileop_proto = out.File
	file_fileop_proto_rawDesc = nil
	file_fileop_proto_goTypes = nil
	file_fileop_proto_depIdxs = nil
}
